name: Execução Manual

on:
  workflow_dispatch:

jobs:
  e2e-tests:

    runs-on: ubuntu-latest

    steps:

      # Clona o repositório
      - name: Checkout do projeto
        uses: actions/checkout@v4

      # Instala Node.js
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # Instala o Yarn
      - name: Instalar Yarn
        run: npm install -g yarn

      # Instala dependências
      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      # Instala Cypress
      - name: Instalar Cypress
        run: npx cypress install

      # Executa os testes
      - name: Executar testes E2E
        run: npx cypress run

      # Salva screenshots como artefato
      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-cypress
          path: cypress/screenshots